from __future__ import annotations

from typing import Final

__all__ = [
    "GOOGLE_CUSTOM_SEARCH_API_KEY",
    "GOOGLE_CUSTOM_SEARCH_ENGINE_ID",
    "GOOGLE_SEARCH_ENABLED",
    "GOOGLE_CUSTOM_SEARCH_MAX_RESULTS",
    "GOOGLE_CUSTOM_SEARCH_CONNECT_TIMEOUT",
    "GOOGLE_CUSTOM_SEARCH_READ_TIMEOUT",
    "GOOGLE_CUSTOM_SEARCH_MAX_RETRIES",
    "GOOGLE_CUSTOM_SEARCH_BACKOFF_FACTOR",
]

from dotenv import load_dotenv

load_dotenv()

import os

GOOGLE_CUSTOM_SEARCH_API_KEY: Final | None = os.getenv("GOOGLE_CUSTOM_SEARCH_API_KEY")
GOOGLE_CUSTOM_SEARCH_ENGINE_ID: Final | None = os.getenv("GOOGLE_CUSTOM_SEARCH_ENGINE_ID")

GOOGLE_SEARCH_ENABLED: Final = bool(GOOGLE_CUSTOM_SEARCH_API_KEY and GOOGLE_CUSTOM_SEARCH_ENGINE_ID)

GOOGLE_CUSTOM_SEARCH_MAX_RESULTS: Final = 10
GOOGLE_CUSTOM_SEARCH_CONNECT_TIMEOUT: Final = 10
GOOGLE_CUSTOM_SEARCH_READ_TIMEOUT: Final = 30
GOOGLE_CUSTOM_SEARCH_MAX_RETRIES: Final = 3
GOOGLE_CUSTOM_SEARCH_BACKOFF_FACTOR: Final = 1
